openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/v1/products/{id}/info/:
    get:
      operationId: v1_products_info_retrieve
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this product.
        required: true
      tags:
      - products
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductInfo'
          description: ''
  /api/v1/products/search/:
    get:
      operationId: v1_products_search_list
      description: ''
      parameters:
      - name: cursor
        required: false
        in: query
        description: The pagination cursor value.
        schema:
          type: integer
      - in: query
        name: name
        schema:
          type: string
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - products
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedProductList'
          description: ''
components:
  schemas:
    AnalogueProduct:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        sber_product_id:
          type: integer
          readOnly: true
        name:
          type: string
          readOnly: true
        country:
          type: string
          readOnly: true
        dosage:
          type: string
          readOnly: true
        drug_form:
          type: string
          readOnly: true
        form_name:
          type: string
          readOnly: true
        is_recipe:
          type: boolean
          readOnly: true
        manufacturer:
          type: string
          readOnly: true
        packing:
          type: string
          readOnly: true
        price:
          type: string
          format: decimal
          pattern: ^\d{0,6}(\.\d{0,2})?$
          readOnly: true
        detail_page_url:
          type: string
          readOnly: true
        analogue_ids:
          type: array
          items:
            type: integer
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            format: int64
          readOnly: true
        medsis_id:
          type: integer
          readOnly: true
        effectiveness:
          type: integer
          readOnly: true
        safety:
          type: integer
          readOnly: true
        convenience:
          type: integer
          readOnly: true
        contraindications:
          type: integer
          readOnly: true
        side_effects:
          type: integer
          readOnly: true
        tolerance:
          type: integer
          readOnly: true
        score:
          type: string
          format: decimal
          pattern: ^\d{0,2}(\.\d{0,1})?$
          readOnly: true
        is_effective:
          type: boolean
          readOnly: true
        is_cheapest:
          type: boolean
          readOnly: true
        is_trustworthy:
          type: boolean
          readOnly: true
      required:
      - analogue_ids
      - contraindications
      - convenience
      - country
      - detail_page_url
      - dosage
      - drug_form
      - effectiveness
      - form_name
      - id
      - is_cheapest
      - is_effective
      - is_recipe
      - is_trustworthy
      - manufacturer
      - medsis_id
      - name
      - packing
      - price
      - safety
      - sber_product_id
      - score
      - side_effects
      - tolerance
    PaginatedProductList:
      type: object
      properties:
        next:
          type: string
          nullable: true
        previous:
          type: string
          nullable: true
        results:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    Product:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        sber_product_id:
          type: integer
          readOnly: true
        name:
          type: string
          readOnly: true
        country:
          type: string
          readOnly: true
        dosage:
          type: string
          readOnly: true
        drug_form:
          type: string
          readOnly: true
        form_name:
          type: string
          readOnly: true
        is_recipe:
          type: boolean
          readOnly: true
        manufacturer:
          type: string
          readOnly: true
        packing:
          type: string
          readOnly: true
        price:
          type: string
          format: decimal
          pattern: ^\d{0,6}(\.\d{0,2})?$
          readOnly: true
        detail_page_url:
          type: string
          readOnly: true
        analogue_ids:
          type: array
          items:
            type: integer
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            format: int64
          readOnly: true
        medsis_id:
          type: integer
          readOnly: true
        effectiveness:
          type: integer
          readOnly: true
        safety:
          type: integer
          readOnly: true
        convenience:
          type: integer
          readOnly: true
        contraindications:
          type: integer
          readOnly: true
        side_effects:
          type: integer
          readOnly: true
        tolerance:
          type: integer
          readOnly: true
        score:
          type: string
          format: decimal
          pattern: ^\d{0,2}(\.\d{0,1})?$
          readOnly: true
        is_effective:
          type: boolean
          readOnly: true
        is_cheapest:
          type: boolean
          readOnly: true
        is_trustworthy:
          type: boolean
          readOnly: true
        analogues:
          type: array
          items:
            $ref: '#/components/schemas/AnalogueProduct'
          readOnly: true
      required:
      - analogue_ids
      - analogues
      - contraindications
      - convenience
      - country
      - detail_page_url
      - dosage
      - drug_form
      - effectiveness
      - form_name
      - id
      - is_cheapest
      - is_effective
      - is_recipe
      - is_trustworthy
      - manufacturer
      - medsis_id
      - name
      - packing
      - price
      - safety
      - sber_product_id
      - score
      - side_effects
      - tolerance
    ProductInfo:
      type: object
      properties:
        cheapest:
          allOf:
          - $ref: '#/components/schemas/Product'
          readOnly: true
        effective:
          allOf:
          - $ref: '#/components/schemas/Product'
          readOnly: true
      required:
      - cheapest
      - effective
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: Session
