# Generated by Django 3.2.3 on 2021-05-29 16:04

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fastupdate=False, fields=["name"], name="name_gin_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
